language: python
cache:
  pip: true
python:
- 3.6
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_7f3885ebfb38_key -iv $encrypted_7f3885ebfb38_iv
  -in gcp-credentials.json.enc -out gcp-credentials.json -d
install:
- pip install -r requirements-dev.txt
script:
- set -eo pipefail
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - S3_BUCKET=hca-cloud-blobstore-travis-test
  - S3_BUCKET_US_EAST_1=hca-cloud-blobstore-travis-test
  - S3_BUCKET_NON_US_EAST_1=hca-cloud-blobstore-travis-test-us-west-1
  - S3_BUCKET_FIXTURES=hca-cloud-blobstore-travis-test-fixtures
  - GS_BUCKET=hca-cloud-blobstore-travis-test
  - GS_BUCKET_FIXTURES=hca-cloud-blobstore-travis-test-fixtures
  - GOOGLE_APPLICATION_CREDENTIALS=gcp-credentials.json
